name: Mini CI/CD (local runner)

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t mini-cicd:latest .

      - name: Stop old container if exists
        run: |
          docker rm -f mini-cicd || true

      - name: Run container
        run: |
          docker run -d --name mini-cicd -p 8080:8080 mini-cicd:latest

      - name: Smoke test
        run: |
          sleep 2
          curl -f http://localhost:8080

